### ISSUE TITLE
Only retrieves one GPS coordinate in the background.

### ISSUE THREAD

**Issue by pmwisdom** [pmwisdom/cordova-background-geolocation-services#1]
Possible Causes:

If you did not acquire a GPS coordinates via navigator.geolocation.getCurrentPosition before going into the background this may happen.

Make sure you are starting the GPS plugin before you into the background (don't start it on your on background listener)

If you set a high distance filter and you have not moved.

**Comment by mbrookes** [comment]
You nailed it in the first case - I haven't acquired GPS before going background. (Which is ironic, as I had foreground GPS working, and switched to a new project to test this!)

I'll tray again with a foreground request first. It would be good to understand why this is necessary (not that it's a problem, and unlikely that you wouldn't normally also have foreground GPS).

**Comment by pmwisdom** [comment]
I believe its a permissions issue but I could be wrong. I could probably request a single position when the user initiates the plugin. I'll test that out.

**Comment by mbrookes** [comment]
Thanks, that worked a treat.  Here's my test code (basically yours with minor tweaks, and wrapped for Meteor):

``` js
if (Meteor.isCordova) {
  Meteor.startup(function () {
    console.log("Cordova startup...");

    function geolocationSuccess(location) {
      console.log("Location: " + JSON.stringify(location))
    }

    function geolocationError(error) {
      console.error("Location error: ", error)
    }

    navigator.geolocation.getCurrentPosition(geolocationSuccess, geolocationError);

    var bgLocationServices =  window.plugins.backgroundLocationServices;

    bgLocationServices.configure({
      desiredAccuracy: 1,                   // Desired Accuracy of the location updates
                                            // (lower means more accurate but more battery consumption)
      distanceFilter: 0,                    // How far you must move from the last point to trigger a location update
      notificationTitle: 'BG Plugin',       // Android only, customize the title of the notification
      notificationText: 'Tracking',         // Android only, customize the text of the notification
      activityType: 'AutomotiveNavigation',
      debug: false,                         // Enable toasts for background-geolocation updates.
      interval: 5,                          // Requested Interval between location updates, in seconds
                                            // (Updates may be less frequent if distanceFilter > 0
      fastestInterval: 1                    // Android only, Fastest interval your app / server can handle updates
    });

    bgLocationServices.registerForLocationUpdates(geolocationSuccess, geolocationError);

//Start the Background Tracker. When you enter the background tracking will start, and stop when you enter the foreground.
    bgLocationServices.start();
  })
}
```

One thing I noticed is that he location data is in a slightly different format to `navigator.geolocation`. Not a big deal, but it might be nice to standardise that.

A few couple of other questions when you get a few minutes:

I get dubugging toasts, but `debug: false` doesn't seem to turn them off? (No audio, but I assume that comment in the example was just a hangover from a previous version...)

What is the metric of `distanceFilter`? Meters?

Is `fastestInterval` also in seconds?

What is the range of values for accuracy? The comment in `BackgroundLocationUpdateService.java` says 0-1000, but the switch statement goes to 10000. Are those discreet values? If so, it might be good to accept a range and round up / down to match the switch perhaps?

Is activityType used? 

(I think that's enough for now! :smile: )

**Comment by pmwisdom** [comment]
Hey @mbrookes, the format is a little easier to deal with and its in line with the christocracy plugin so I thought it might be better to keep that part consistent.  I'm using the same format with my atmosphere geolocation package .

I fixed that debug toast already, if you change the commit you added the plugin with to the most recent one that should be fixed! (Wouldn't it be great if meteor allowed you to just specify the git repo and not by commit!)

Distance Filter is in meters, i'll put that in the docs soon, fastest Interval is in milliseconds.

Ah and I forgot to change that switch statement, I changed it on iOS but forgot android, thanks for reminding me. 

I'll double check on activityType later but you don't get much difference if you change the type.

**Comment by mbrookes** [comment]
Ah, thanks, I'll update. 

And there I was creating a PR for the standard data format. :) (It isn't really any harder to use, and switching foreground to background with different formats is more painful - but your project, so your call! :smile: 

Dumb question - why would one use a cordova plugin for foreground geolocation when navigator.geolocation is baked in?

**Comment by pmwisdom** [comment]
To be honest I just found it annoying that the location object was nested when its only passing back ~ 7 fields. Easier to do location.latitude vs location.coordinates.latitude. If you want to have it be the same across both you could use my atmosphere plugin for foreground =). 

On android, it actually doesn't do anything, just forwards the calls, but on iOS the cordova plugin does a lot more.

**Comment by mbrookes** [comment]
Okay, thanks - I'll use your plugin for sure for foreground when I get to iOS. For now I'll just flatten the navigator.location result to match. And you're right, it is daft that it's nested!
