### ISSUE TITLE
iOS build fails on build.phonegap.com 

### ISSUE THREAD

**Issue by ivanssa** [pmwisdom/cordova-background-geolocation-services#17]
First congratulations for the work, as reported in https://github.com/pmwisdom/cordova-background-geolocation-services/issues/14 the plugin seems to work perfectly on Android but in the version for IOS an error occurs when compiling the application by build.phonegap.com, I've tried everything I'm more than a month searching for a solution but unfortunately not found, would be very happy if someone could help the community.

![erross](https://cloud.githubusercontent.com/assets/3166174/14933626/5c52efc8-0e6b-11e6-9dd8-490b703a8262.jpg)

build.phonegap Log Error

```
=== BUILD TARGET MyApp OF PROJECT MyApp WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
Swift is unavailable on iOS earlier than 7.0; please set IPHONEOS_DEPLOYMENT_TARGET to 7.0 or later (currently it is '6.0').
warning: skipping file '/project/com.google.android.gms:play-services-location:+' (unexpected file type 'file' in Frameworks & Libraries build phase)
warning: skipping file '/project/com.google.android.gms:play-services-location:+' (unexpected file type 'file' in Frameworks & Libraries build phase)

** BUILD FAILED **


The following build commands failed:
    Check dependencies
(1 failure)
```

**

When upgrading to <preference name = "deployment-target" value = "7.0" /> or 8.0 continues giving error with another code as the log below:**

```
** BUILD FAILED **

The following build commands failed:
    CompileSwift normal arm64 /project/RumoApp/Plugins/org.flybuy.cordova.background-location-services/CDVBackgroundLocationServices.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

When upgrading to `<preference name = "deployment-target" value = "7.0" />` or 8.0 continues giving error with another code as the log below:

When updating the version of Phonegap in config.xml `<preference name = "phonegap-version" value = "cli-6.1.0" />` the app is finally compiled without errors, but when I try to open the app on the device it opens and closes unexpectedly.

**Comment by pmwisdom** [comment]
Hey @ivanssa, thanks for reporting this as still an issue. I will try my best to debug phonegap build this week.

**Comment by ivanssa** [comment]
Hi @pmwisdom believe the problem is related to the compiled code Swift even tried to convert the code to Objective-C but it still fails, you could rewrite the code in Objective-C or based on IOS free version of Chris plugin it works perfectly, so finally we would have one free plugin for Android and IOS.

**Comment by pmwisdom** [comment]
@ivanssa It is the compilation of swift, or rather its the hook script that's failing for IOS build. I wouldn't consider re-writing it in objective-c or using chris's plugin because my plugin doesn't use significant changes library, and my requirements barred me from using it. It also only fails on phonegap build, regular ios builds work just fine. So fixing the hook will fix everyone's problem, which is a lot easier than a rewrite. 

You are more than welcome to fork the plugin and replace my swift files with chris's plugin files. The API is almost the same.

**Comment by ivanssa** [comment]
Cool, I understand, I was thinking of doing as recommended a folk and try to run the two plugins to have an alternative until you solve pgb errors, thanks for the reply.

**Comment by pmwisdom** [comment]
I know this has been awhile in the coming, but I tried a bunch of different things and it seems like PGB just doesn't support swift yet. I'm going to close this for now since PGB seems to be the problem, not the plugin.

https://github.com/phonegap/build/issues/521
