### ISSUE TITLE
play service location not found

### ISSUE THREAD

**Issue by NadirBertolasi** [pmwisdom/cordova-background-geolocation-services#18]
Hi, after launching c`ordova plugin add https://github.com/pmwisdom/cordova-background-geolocation-services.git` I get:

```
Error: Uh oh!
"workspace_ionic/comeInComo_gps/plugins/org.flybuy.cordova.background-location-services/com.google.android.gms:play-services-location:+" not found!
```

In sdk manager those modules are correctly installed. Can you help me? 

Thank you

**Comment by pmwisdom** [comment]
Make sure you have:

Android Support Repository
Android Support Library

Google Play Services
Google Repository

**Comment by NadirBertolasi** [comment]
Actually I have them all. I think I should add play services to the generated android project

![schermata 2016-05-09 alle 20 19 42](https://cloud.githubusercontent.com/assets/19230951/15123286/6b573a96-1623-11e6-8044-9a34d5663886.jpg)

**Comment by pmwisdom** [comment]
Yeah I'm not sure why its looking in the plugin folder for that library, it should be looking for it where your android SDK is installed. Unless Ionic does it differently, I haven't used Ionic in a very long time.
