### ISSUE TITLE
Does it work well?

### ISSUE THREAD

**Issue by rafasegat** [pmwisdom/cordova-background-geolocation-services#21]
Hey,

Great plugin. I have a question.

Does this plugin works well?? Whats pros and cons against ( https://github.com/transistorsoft/cordova-background-geolocation-lt ) ?!

Thanks
Raf

**Comment by pmwisdom** [comment]
Does it work well is a pretty objective question, It works well for my purposes.

The plugin you linked doesn't support android, unless you pay for a license so thats the most obvious difference. 

My IOS version of the plugin is drastically different, christocracy's plugin uses significant changes library and I do not. Which basically means, you'll get more constant data points with my plugin, but worse battery life if you tell the plugin to act aggressively. You should do some research on IOS Significant Changes Library for more information on which plugin is right for you.

**Comment by lpender** [comment]
I noticed you have a new parameter in `1.0.3` called `useActivityDetection`. Does this mean that you are using the Significant Changes Library now?

Thanks!

**Comment by pmwisdom** [comment]
Nope, It does not use the significant locations library as its primary geo-location strategy.

It's using the [CMMotionActivity library](https://developer.apple.com/library/ios/documentation/CoreMotion/Reference/CMMotionActivityManager_class/index.html#//apple_ref/occ/cl/CMMotionActivityManager), which is the equivalent of the android detected activities library. It allows me to detect if the user is standing still to a degree, and if so I shut off the GPS until it detects that you are active again. I improved ios battery in other ways too.
