### ISSUE TITLE
Android location updates only triggering once when app is suspended

### ISSUE THREAD

**Issue by gijsstegehuis** [pmwisdom/cordova-background-geolocation-services#23]
I can't get android to send continuous location updates in the background.
It only fires once when the device is suspended.

This is the configuration i am running:

``` javascript
bgLocationServices.configure({
                 // Both
                 desiredAccuracy: 20000, // Desired Accuracy of the location updates (lower means more accurate but more battery consumption)
                 distanceFilter: 0.1, // (Meters) How far you must move from the last point to trigger a location update
                 debug: true, // <-- Enable to show visual indications when you receive a background location update
                 interval: 1000, // (Milliseconds) Requested Interval in between location updates.

                 // Android Only
                 fastestInterval: 500, // <-- (Milliseconds) Fastest interval your app / server can handle updates
                 useActivityDetection: false // Uses Activitiy detection to shut off gps when you are still (Greatly enhances Battery Life)
            });
```

Even when i am running it through `startAggressiveTracking` it doesnt work.
Any thoughts on this?

**Comment by pmwisdom** [comment]
That's typical behavior of what happens if you don't retrieve at least one GPS coordinate in the foreground before using the background plugin. Make sure your successfully doing that.

**Comment by gijsstegehuis** [comment]
I did actually receive one coordinate up front. It seems to be working now, though i don't exactly now why.

**Comment by pmwisdom** [comment]
@gijsstegehuis Glad to hear, feel free to close if you feel like its resolved.
