### ISSUE TITLE
Launch failed with Release scheme

### ISSUE THREAD

**Issue by HPaulowicz** [pmwisdom/cordova-background-geolocation-services#25]
Thank you for useful plugin!

However, I got issue on iOS using it with release scheme.
App on beta-check for TestFlight was rejected twice using this plugin.

Error log:

```
Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x0000000120051088
Triggered by Thread:  0

Filtered syslog:
None found

Dyld Error Message:
Dyld Message: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /var/containers/Bundle/Application/AB5B444F-2EB9-481C-8F65-2B410A06532D/Wingr.app/Wingr
  Reason: image not found
  Dyld Version: 390.7
```

Please, share any ideas what the reason of crash.
![2016-06-10 15 20 43](https://cloud.githubusercontent.com/assets/2038540/15993599/993736a8-30b0-11e6-8b5c-8832199c1099.png)

**Comment by pmwisdom** [comment]
Hi @HPaulowicz can you describe what you mean by "release scheme" I'm not sure what that is. Also what is beta-check? Did they share information about why it was rejected?

I have two applications in production right now using the plugin so there shouldn't be any reason for it getting rejected.

**Comment by HPaulowicz** [comment]
Hi @pmwisdom! Thanks for response.

There are few screenshots to make it clear (sorry for Russian language on pics).

The app crashes on launch when Build Configuration set to "Release" in xCode. TestFlight also using Release Build Configuration and the app crashes on launch. As I figured out crashes caused by the plugin. This is only one Swift plugin I using and without it everything goes smooth. Running an app on my own device while Build Configuration set to "Debug" goes smooth too.
Error log from the response from Apple I posted before.

I can't figure out what the reason of crash with the plugin.

![2016-06-13 14 52 59](https://cloud.githubusercontent.com/assets/2038540/16021233/25a16c8c-3177-11e6-9911-ac80d33fc732.png)
![2016-06-13 14 55 50](https://cloud.githubusercontent.com/assets/2038540/16021234/25a2ae44-3177-11e6-9add-5217ac3f21c2.png)
![2016-06-13 14 56 37](https://cloud.githubusercontent.com/assets/2038540/16021235/25a5ab4e-3177-11e6-97d0-69ef2510f905.png)

**Comment by pmwisdom** [comment]
@HPaulowicz Googling that error message gave me:

http://stackoverflow.com/questions/26024100/dyld-library-not-loaded-rpath-libswiftcore-dylib.

> For me none of the previous solutions worked. We discovered that there is an "Embedded Content Contains Swift Code" flag in the Build Settings that needs to be set to YES. It was NO by default!

**Comment by HPaulowicz** [comment]
@pmwisdom, it already done. Anyway getting crash. Screenshots below.
You had never this issue?

![2016-06-13 15 56 11](https://cloud.githubusercontent.com/assets/2038540/16022927/f39faeac-317f-11e6-85c4-ab479be6a56c.png)
![2016-06-13 15 56 54](https://cloud.githubusercontent.com/assets/2038540/16022928/f3a18768-317f-11e6-90e1-287ee25d6b65.png)

**Comment by HPaulowicz** [comment]
Solved.
http://stackoverflow.com/a/33648095/3189097

![2016-06-13 16 19 34](https://cloud.githubusercontent.com/assets/2038540/16023558/e1a0a38e-3182-11e6-9834-1fbebbf57d31.png)

**Comment by pmwisdom** [comment]
@HPaulowicz glad it got figured out. I do remember seeing that issue on cordova which got solved for me on a later release.
