### ISSUE TITLE
Hook for actity function

### ISSUE THREAD

**Issue by BioPhoton** [pmwisdom/cordova-background-geolocation-services#27]
Hi @pmwisdom,

This plugin is awesome! Looks at graphs and so on, i like it a lot!!!

The activity tracking feature is very interessting. I think it would be a cool idea to provide a hook/callback for the function that determines the most probable activity and keep your current logic als default.

It would 
first go inline with just providing the position as is and keep Secret Sauce to the programmer, 
and second would uncover device hardware problems (sometimes phones are flaky with hardware stuff)

**Comment by pmwisdom** [comment]
Hey @BioPhoton. I'm not sure what your requesting exactly.

The Activity Detection is straight from Android / iOS libraries, so the results are non-modifiable. All those algorithms are through DetectedActivities / CoreMotion libraries.

And all activity results are passed back through the activity callback, so you can ascertain the "most probable activity" through the confidence levels passed back with the array of activities.
