### ISSUE TITLE
background service crashed when app is closed 

### ISSUE THREAD

**Issue by cosmicanant** [pmwisdom/cordova-background-geolocation-services#28]
Hi 
I am wondering if I can track location even if the app is closed. Currently after closing app, background service is also get crashed. Please let me know if somehow we can do this.

**Comment by pmwisdom** [comment]
@cosmicanant : Do you mean closed as in force closed by user?

**Comment by pmwisdom** [comment]
Closing this as its been answered in other places.
If the user force closes the app, the background service will turn off by design.
