### ISSUE TITLE
Can't install using plugman

### ISSUE THREAD

**Issue by jor3l** [pmwisdom/cordova-background-geolocation-services#3]
Hello there!

When I try to install this using plugman I get an error saying that there is no AndroidManifest.xml, you have any idea why is this happening?. 

Thanks!

**Comment by jor3l** [comment]
Works with 

```
cordova plugin add https://github.com/pmwisdom/cordova-background-geolocation-services.git
```

**Comment by pmwisdom** [comment]
Hey @jor3l, yeah thats the right way to install it. I've never tried it out with plugman. So you got it to work?

I'll put the cordova plugin command in the README for future users.
