### ISSUE TITLE
Service not working in background 

### ISSUE THREAD

**Issue by Souras** [pmwisdom/cordova-background-geolocation-services#30]
Hi, Service is not working when i set app in foreground. Both Service are registerForLocationUpdates and registerForActivityUpdates trigger once in background. using android marshmallow and this is ionic  fresh application created to test this service.

**Comment by pmwisdom** [comment]
@Souras : 

Did you attempt to fetch a geolocation point using navigator.geolocation.getCurrentPosition before transitioning to the background? 

Where are you "Starting" the tracking?

**Comment by Souras** [comment]
Your service working very fine when i set "useActivityDetection" to false. Otherwise it is giving [STILL:100] then nothing while location is changing. I am using Mock Location. Is this the catch?

**Comment by Souras** [comment]
Actually i do not know about the Activity Recognition. I was placing my device on table checking log on system that why this was showing [STILL:100]  and no location after that. Sorry to bother you and thanks for the service.
