### ISSUE TITLE
plugin stopped working in iOS

### ISSUE THREAD

**Issue by icedice** [pmwisdom/cordova-background-geolocation-services#31]
Plugin stopped working in iOS. Im getting "Syntax error: Unexpected identifier 'exec'" at line 2 in BackgorundLocationServices.js

Derive from that error (I guess) I get " Error org.flybuy.cordova.background-location-services.BackgroundLocationServices does not exist"

I'm about to use the plugin in a production app, I would appreciate it a lot if you could look in to the problem.

**Comment by pmwisdom** [comment]
@icedice how did you add the plugin to your project?

Make sure your not on this https://github.com/pmwisdom/cordova-background-geolocation-services/commit/bcb6115dd90fc36c20f9aa4c1f6d96378ba15852 commit.

**Comment by pmwisdom** [comment]
Going to close this for now, Please re-open if its still a problem.
