### ISSUE TITLE
iOS build error: Swift is unavailable on iOS earlier than 7.0; please set IPHONEOS_DEPLOYMENT_TARGET to 7.0 or later (currently it is '6.0').

### ISSUE THREAD

**Issue by ghost** [pmwisdom/cordova-background-geolocation-services#32]
Cordova ios 4.1.x
Ionic CLI 1.7.16

When i try to build using CLI "ionic build ios" get below error:

Swift is unavailable on iOS earlier than 7.0; please set IPHONEOS_DEPLOYMENT_TARGET to 7.0 or later (currently it is '6.0').

**Comment by pmwisdom** [comment]
@appplumbr 

Try upgrading your Cordova CLI.

```
npm update -g cordova
```
