### ISSUE TITLE
swiping the app away on recent apps kills background

### ISSUE THREAD

**Issue by clement360** [pmwisdom/cordova-background-geolocation-services#35]
The persistent notification disappears whenever the application is closed via the recent app menu on android (did not test ios). Does this mean that the background process is dead or is it still running?

**Comment by pmwisdom** [comment]
@clement360 Yes, swiping the app away destroys the background process. Without the webview, the service would have nowhere to send the location updates.

**Comment by ghost** [comment]
@pmwisdom can this plugin work and track locations even when the app is closed? Just like https://github.com/transistorsoft/cordova-background-geolocation-lt this plugin?
