### ISSUE TITLE
Error trying to add package --> meteor add mirrorcell:background-geolocation-plus

### ISSUE THREAD

**Issue by syafiqFiqq** [pmwisdom/cordova-background-geolocation-services#4]
im trying to add your package using the command
--> meteor add mirrorcell:background-geolocation-plus

but got this error 
=> Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: mirrorcell:background-geolocation-plus 1.1.4

unknown package: isobuild:compiler-plugin
Required by: ecmascript 0.1.3-plugins.1

can you assist me on this error.. Thanks and
can i know where can i see your meteor code instead of the cordova code..

**Comment by pmwisdom** [comment]
I'll try a fresh install tomorrow. What version of meteor are you running it on?

Didn't realize that it was pointed to this repo. I'll fix that tomorrow.

Here's the repo for the meteor wrapper.

https://github.com/pmwisdom/meteor-background-geolocation-services

**Comment by syafiqFiqq** [comment]
im on Meteor version  1.1.0.3 .. Orite, will wait for your trial result..
thanks..

**Comment by pmwisdom** [comment]
@syafiqFiqq  I believe the reason was that ECMAscript was a dependency of the package and you are on sub meteor version sub 1.2. I removed ecmascript dep, since we weren't using es6. Please try the new version on atmosphere.

https://github.com/pmwisdom/meteor-background-geolocation-services/commit/950bc5fd2dec5a609c6e99a90f49d37466368784

**Comment by syafiqFiqq** [comment]
i already give it a try and it give me this error

Error while running for mobile platforms: Error running  
/Users/syafiqFiqq/.meteor/packages/meteor-tool/.1.1.4.1ou5jw4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Error: 404 Not Found: cordova-plugin-geolocation
at RegClient.<anonymous>
(/Users/syafiqFiqq/.meteor/packages/meteor-tool/.1.1.4.1ou5jw4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:14)
at Request._callback
(/Users/syafiqFiqq/.meteor/packages/meteor-tool/.1.1.4.1ou5jw4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:246:65)
at Request.self.callback
(/Users/syafiqFiqq/.meteor/packages/meteor-tool/.1.1.4.1ou5jw4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:236:22)
at Request.emit (events.js:98:17)
at Request.<anonymous>
(/Users/syafiqFiqq/.meteor/packages/meteor-tool/.1.1.4.1ou5jw4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1142:14)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous>
(/Users/syafiqFiqq/.meteor/packages/meteor-tool/.1.1.4.1ou5jw4++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/request.js:1096:12)
at IncomingMessage.emit (events.js:117:20)
at _stream_readable.js:944:16
at process._tickCallback (node.js:442:13)

it seem that it cant find the cordova-plugin-geolocation.. any idea on this? Thanks

**Comment by pmwisdom** [comment]
Unfortunately I just tested this out and to use this plugin with less than meteor 1.2, your going to have to download / fork this package locally and replace the cordova depends in package.js with : 

Cordova.depends({
  "cordova-plugin-geolocation" : "https://github.com/apache/cordova-plugin-geolocation/tarball/79bdb044bef0a2b8e5470b32af8db9f7f38c9fb3",
  "org.flybuy.cordova.background-location-services" : "https://github.com/pmwisdom/cordova-background-geolocation-services/tarball/bd1d3d2e8a65585614f0d2278ecd0cfada450652"
});

That, or you can upgrade meteor and it will work.
