### ISSUE TITLE
Receive Geolocation Updates More Often

### ISSUE THREAD

**Issue by anshul-chandan** [pmwisdom/cordova-background-geolocation-services#40]
Hi! I need to get the user's geolocation while the app is in the background at a rate faster than once every second. However, I can't get the plugin to do so in iOS and I cannot even receive updates faster than once every 9 seconds on Android (even if I manually lower the interval). Any suggestions? My code is below:
` // Run when the device is ready
    document.addEventListener('deviceready', function () {

```
    // Android customization
    // To indicate that the app is executing tasks in background and being paused would disrupt the user.
    // The plug-in has to create a notification while in background - like a download progress bar.
    cordova.plugins.backgroundMode.setDefaults({
        title:  'Notification',
        text:   'Text'
    });

    var bgLocationServices = window.plugins.backgroundLocationServices;

    // Enable background mode
    cordova.plugins.backgroundMode.enable();

    // Called when background mode has been activated
    cordova.plugins.backgroundMode.onactivate = function() {

        bgLocationServices.configure({
            //Both
            desiredAccuracy: 1, // Desired Accuracy of the location updates (lower means more accurate but more battery consumption)
            distanceFilter: 1, // (Meters) How far you must move from the last point to trigger a location update
            debug: false, // <-- Enable to show visual indications when you receive a background location update
            interval: 1000, // (Milliseconds) Requested Interval in between location updates.
            useActivityDetection: true, // Uses Activitiy detection to shut off gps when you are still (Greatly enhances Battery Life)

            //Android Only
            notificationTitle: 'Victorise Geolocation', // customize the title of the notification
            notificationText: 'Tracking', //customize the text of the notification
            fastestInterval: 1000, // <-- (Milliseconds) Fastest interval your app / server can handle updates
        });

        //Register a callback for location updates, this is where location objects will be sent in the background
        bgLocationServices.registerForLocationUpdates(function(location) {
                // console.log("We got an BG Update" + JSON.stringify(location));
                currPosLatLng = new google.maps.LatLng({lat: location.latitude, lng: location.longitude});
                posMarker.setPosition(currPosLatLng);
            },
            function(err) {
                console.log("Error: Didnt get an update", err);
        });


        bgLocationServices.start();
        //$scope.millisecondsInterval = 1000;
    };

    cordova.plugins.backgroundMode.ondeactivate = function() {
        $scope.secondsAdder = 0.01;
        bgLocationServices.stop();

        //$scope.millisecondsInterval = 10;
    };

}, false);`
```

**Comment by pmwisdom** [comment]
Short answer is, no, if you've set the settings to as aggressive as possible thats about how many updates you will get. On android especially, I can't force it to give you more coordinates. You basically request the interval you want and android may or may not give you coordinates at that interval. This is especially true if you are not actively moving.

What scenario do you need to get gps positions more than once a second? That seems like overkill to me.

**Comment by anshul-chandan** [comment]
Thanks for the response! I guess more than a second is overkill but I can't even get that on Android...and sometimes when I try to make the settings as aggressive as possible it won't even return any locations on my Android device. Basically, the app is getting the user's position and comparing it to markers on a map that they have previously placed and then either playing a sound or sending a message to a bluetooth device to perform some action. However, I need the location to be received as soon and as accurately as possible, otherwise the user might pass the marker without receiving the desired action, which would basically render the app useless.

**Comment by pmwisdom** [comment]
@anshul-chandan I'll try to take a look soon, been very busy!

In the mean time have you tried to turn activity detection off? Set distanceFilter and desiredAccuracy to 0 as well.

**Comment by pmwisdom** [comment]
@anshul-chandan Also I just noticed that your using backgroundMode. You probably shouldn't use both that plugin and this one at the same time. They share a common background scheme.

**Comment by anshul-chandan** [comment]
I'm currently using background mode to compare the position I get from the background to another LatLng point and then play a sound or send a signal to a bluetooth device if the user is near other LatLng point...any ideas of what I could do instead of using the backgroundMode plugin?

**Comment by anshul-chandan** [comment]
Also I do need to get the location more than once a second because it's a timing thing, I want the user to be able to know when they have received a better time in completing the task than someone else, even if it's just by a few hundred milliseconds...I can worry about this later but if you could know of a way I could do this, that'd be nice

**Comment by anshul-chandan** [comment]
Okay so I actually see what you're saying now, I took out the background mode plugin and it's starting to work much better! The only thing is that it takes time to speed up the geolocation retrieval (about a minute or two before it gets down to 1 second), I'm guessing this is a warm up time so I'm wondering if there's a way to minimize that warm up time...

**Comment by pmwisdom** [comment]
What I meant by that is,  you can basically think of my plug in has having the background mode plugin inside of it.  They both use a service connection to bind the Web view to a foreground service.

**Comment by pmwisdom** [comment]
I won't have more info about the interval issue for another week or so,  I need to do testing once I have some free time.

**Comment by anshul-chandan** [comment]
Alright, that's fine, thanks for the help!

**Comment by anshul-chandan** [comment]
It seems like I may have gotten it to work, I'll do some more testing and close the issue if it's consistent
