### ISSUE TITLE
How to implement typical use-case?

### ISSUE THREAD

**Issue by RikdeBoer** [pmwisdom/cordova-background-geolocation-services#43]
I would like a user to be able to kick off background location (through this plugin), then have them spend some time on WhatsApp or whatever, then move to a second app/web page I write, where they can see the route they travelled as a series of lat/lon or on a map.

_Q: How does the background geolocation service communicate the lat/lon coords it received from the phone’s hardware to another (foreground) process?_

a) Via memory? Does some sort of shared name space exist on Android or iOS that one process can write to and another can read from? I suspect not.

b) Via a cookie? Don’t think so. Cookie is bound to document. 

c) Via a file on the mobile that the background process writes to and the foreground process reads from. Cannot write files in browser js (can in node.js apparently).

d) Via a lightweight database, preferably one that is easy to use with javascript, maybe https://pouchdb.com or  http://alasql.org ? Depends on underlying storage mechanism used? 

e) Via a web server? The background process could HTTP POST/PUT ( XMLHttpRequest) the coords to a server (which presumably stores this in a db) and the foreground process could GET it from there.

Thoughts anyone?

**Comment by pmwisdom** [comment]
@RikdeBoer if I understand correctly you have a cordova application thats using this plugin and you'd like the user to be able to view their trip in a seperate website?

I guess my first question is why can't they just see their route in the cordova application?

If you do want to have the route viewable via a secondary website you will need to store locations in some type of database online. You could do this via node, or with a firebase DB. You might check out Meteor if you want a easy platform to base it on.

**Comment by RikdeBoer** [comment]
> I guess my first question is why can't they just see their route in the cordova application?

They can while in the foreground. When they go to WhatsApp (or any other app) and come back, they've lost the route "trail" of the time they were on WhatsApp. However the background process via your plugin will have recorded every step. 

I have fiddled more with the code and just realised a solution. 

Thanks for the hints! Got it now!
