### ISSUE TITLE
What do you use to view the Log.e(), Log.d() etc. msgs on the Android device itself?

### ISSUE THREAD

**Issue by RikdeBoer** [pmwisdom/cordova-background-geolocation-services#47]
I've installed [aLogCat](https://play.google.com/store/apps/details?id=org.jtb.alogcat), but it doesn't seem to display the Log msgs initiated from this plugin...

**Comment by pmwisdom** [comment]
https://developer.android.com/studio/profile/android-monitor.html 

Thats probably your best bet. You can filter by log tags.

**Comment by RikdeBoer** [comment]
Thanks for the tip.
So nothing available on the phone itself? Ideally I want to be able to walk/drive around and see error/debug/info msgs as they happen.  Without also dragging a laptop with me.

**Comment by pmwisdom** [comment]
If you set debug = true in the config you'll receive toast messages on your phone screen, even in the background whenever you get an update. You'll also get updates on whether the phone thinks you are still or not ( activity detection ).

**Comment by RikdeBoer** [comment]
Yep, I found those. And very handy they've been.
I just want more. Just while I'm getting my brain around this great plugin!

**Comment by pmwisdom** [comment]
Your welcome to fork it and add some, they're very very easy to instantiate! Other than that logcat will show you a bunch more logs if your near a computer.
