### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'window.plugins.backgroundLocationServices')

### ISSUE THREAD

**Issue by Balloota** [pmwisdom/cordova-background-geolocation-services#48]
Hi pmwisdom, why am I getting undefined on  _window.plugin_? I tried this on _cordova_ and on _ionic._ Same thing... Should I use meteor? Any idea what am i doing wrong here?

**Comment by Balloota** [comment]
ah by the way i am using ios and i see it on simulator and device too...

**Comment by pmwisdom** [comment]
Not sure if thats a typo, but its window.plugin**s** not window to plugin.

You say you see it on IOS device, so are you just not seeing it on android?

**Comment by Balloota** [comment]
oh yea it is a typo.. this is what i have exactly:
_var bgLocationServices =  window.plugins.backgroundLocationServices;_

I am a JS noob but at least i got the other example which you refer to from christocracy, up and running. I am looking forward if I can get to the android side soon... Cheers

**Comment by pmwisdom** [comment]
@SleepyNab So everything worked alright? Can I close this?

**Comment by Balloota** [comment]
No actually it didn't yet, that was a typo in the post and not not in the code. 
The code is: var bgLocationServices = window.plugins.backgroundLocationServices;
And is hitting an error over this very first statement. Reason is plugins is not in window... I am thinking for some reason the plugin does not load... Please let me know if there is some info I can provide or the way to debug loading the plugin(s) in the framework. Thanks

**Comment by pmwisdom** [comment]
I need to know which platform your having trouble on to help you out further.  Ios / android / both.

**Comment by Balloota** [comment]
I tried iOS with emulator and device (iPhone 6/iOS 9.3.3).. 
I also tried building it using Cordova and Ionic CLI's, then when I debug with safari setting a BP on that line I see that plugins isn't there inside window... When executing it, the undefined error pops...

Haven't tried android. Actually I do not have the environment set for android yet.

**Comment by pmwisdom** [comment]
Not much to go on hm. I'm guessing either there was a build error... 

When you build the project are there any warnings / errors associated with the build?  What version of xcode / Cordova / ionic are you running?

**Comment by Balloota** [comment]
My bad, i figured it out: I had put the code in a separate js file and loaded from index.html before app.initialize()
Therefore the plugin was not 'yet' available...
Many Thanks!

**Comment by pmwisdom** [comment]
Ah! yes, should have thought of that first, I'm glad you figured it out!
