### ISSUE TITLE
"class not found" error on registerForLocationUpdates ..

### ISSUE THREAD

**Issue by backface** [pmwisdom/cordova-background-geolocation-services#5]
I am trying to registerForLocationUpdates, however I do immediately get a "class no found"-error delivered through the error callback.
Am I missing something? 
I am on cordova 5.4.1 with ionic and both Google Play Services Google Repository are installed.

**Comment by pmwisdom** [comment]
Android Platform?

Please try and also install Android Support Library v23.1.1, and Android Support Repository v25 from the Android SDK manager and see if that fixes the problem.

**Comment by backface** [comment]
Installed platforms: android 5.0.0

support library and repository are up to date.

I somehow overlooked there are errors on building the plugin for the platform - seems to be due to deprecated http classes:

.....//platforms/android/src/com/flybuy/cordova/location/BackgroundLocationUpdateService.java:9: error: package org.apache.http does not exist
import org.apache.http.HttpResponse;
                      ^
.....//platforms/android/src/com/flybuy/cordova/location/BackgroundLocationUpdateService.java:10: error: package org.apache.http.client.methods does not exist
import org.apache.http.client.methods.HttpPost;
                                     ^
.....//platforms/android/src/com/flybuy/cordova/location/BackgroundLocationUpdateService.java:11: error: cannot find symbol
import org.apache.http.conn.scheme.Scheme;
                                  ^
  symbol:   class Scheme
  location: package org.apache.http.conn.scheme
.....//platforms/android/src/com/flybuy/cordova/location/BackgroundLocationUpdateService.java:12: error: cannot find symbol
import org.apache.http.conn.scheme.SchemeRegistry;
                                  ^
  symbol:   class SchemeRegistry
  location: package org.apache.http.conn.scheme
v/platforms/android/src/com/flybuy/cordova/location/BackgroundLocationUpdateService.java:15: error: package org.apache.http.entity does not exist
import org.apache.http.entity.StringEntity;
                             ^
.....//platforms/android/src/com/flybuy/cordova/location/BackgroundLocationUpdateService.java:16: error: package org.apache.http.impl.client does not exist
import org.apache.http.impl.client.DefaultHttpClient;
                                  ^
...../platforms/android/src/com/flybuy/cordova/location/BackgroundLocationUpdateService.java:17: error: package org.apache.http.impl.conn does not exist
import org.apache.http.impl.conn.SingleClientConnManager;
                                ^
7 errors
 FAILED

FAILURE: Build failed with an exception.

**Comment by pmwisdom** [comment]
Ah, ok thanks for the insight, we aren't using HTTP anymore so I will attempt to remove the dependencies later today if I have time.

**Comment by pmwisdom** [comment]
@backface  Ok, fixed, try latest commit.

**Comment by Shadowstep33** [comment]
I am receiving these errors but I installed directly from cocoon.io. Is it possible their repo is out of date?
