### ISSUE TITLE
When to `start` and `stop`?

### ISSUE THREAD

**Issue by lpender** [pmwisdom/cordova-background-geolocation-services#53]
Thanks again for your lovely plugin.

From the `readme`:

```
//Start the Background Tracker. When you enter the background tracking will start, and stop when you enter the foreground.
bgLocationServices.start();


///later, to stop
bgLocationServices.stop();
```

I assume that you call `start()` as soon as you want background location services to engage.

Curious--when would anybody ever call `stop()`? 

The time I can think of is: Right before calling `start()`...

Are these methods synchronous?

**Comment by harithFED** [comment]
i use stop when i logout.
