### ISSUE TITLE
Update when not moving

### ISSUE THREAD

**Issue by soesujith** [pmwisdom/cordova-background-geolocation-services#58]
Great job, thank you for the plugin.
My questions is, in the background would this plugin send location update at the given interval when the device is not moving(still)?
Also, is there a way to detect when plugin exists bg mode?
Thank you

**Comment by pmwisdom** [comment]
Try turning useActivityDetection to false.

What do you mean by when plugin exists? When its running maybe?

**Comment by srsarcasmo** [comment]
como se implementa este plugin?
