### ISSUE TITLE
How to remove notification title and text on Android?

### ISSUE THREAD

**Issue by Chidan** [pmwisdom/cordova-background-geolocation-services#6]
Hi, thanks for the plugin.
I wold like to remove the notification text and title, could you please let me know how to do it?
Also I  keep on getting user activity status like start recording and stop recording when the app is running in the background, how to stop it?

Regards,
Chidan

**Comment by pmwisdom** [comment]
I wold like to remove the notification text and title, could you please let me know how to do it?
1. You can't remove the notification text / title. That's unfortunately the only way to be sure that the OS will not kill the service. However, with that said, I have not tried it without a notification. The code you would have to modify are the ones pertaining to startForeground and stopForeground

Also I keep on getting user activity status like start recording and stop recording when the app is running in the background, how to stop it?
1. Set debug = false.

**Comment by Chidan** [comment]
Thanks..
