### ISSUE TITLE
Can I change navigator.geolocation .... ?

### ISSUE THREAD

**Issue by aveliks** [pmwisdom/cordova-background-geolocation-services#63]
In example You use navigator.geolocation object, but can I use another geoloc objects from another plugins for starting use Your plugin?

**Comment by aveliks** [comment]
I see that You use cordova-plugin-geolocation as linked plugin . There is one big trouble with navigator.geolocation object in WebKit based apps:
http://stackoverflow.com/questions/23383750/phonegap-geolocation-sometimes-not-working-on-android/39173044#39173044

I get same problem in my HUAWEI P8 Lite .

This is common old problem. Therefore I start use another plugin for geoloc.

Question is: can I use another plugin and use Your plugin  in same time ?

**Comment by pmwisdom** [comment]
Your definitely right. There's no reason to have that plugin in there. I'll be removing it.

**Comment by aveliks** [comment]
Wow! Yeppp , You get me The Big Hope ! 

I 'll wait ....

**Comment by pmwisdom** [comment]
@aveliks If you wa

**Comment by pmwisdom** [comment]
New version has it removed. Cheers!
