### ISSUE TITLE
How to set the variable "ALWAYS_USAGE_DESCRIPTION" for ios 10?

### ISSUE THREAD

**Issue by luis-ordering** [pmwisdom/cordova-background-geolocation-services#65]
I need to set the variable "ALWAYS USAGE DESCRIPTION" that is required in the Appstore from ios 10 something like:

`cordova plugin add cordova-plugin-camera --variable ALWAYS_USAGE_DESCRIPTION="For use."`

Someone can tell me how?
Thanks for help!

**Comment by pmwisdom** [comment]
This is currently not configurable.
