### ISSUE TITLE
Please create a standalone activity recognition plugin

### ISSUE THREAD

**Issue by singhketan** [pmwisdom/cordova-background-geolocation-services#7]
I haven't used the plugin yet, but I can see that it has activity recognition built in. It's interesting to note that there isn't any activity recognition cordova plugin for Android out there. It would be really great if you could create a dedicated plugin for that.

If you decide to do so, please let me have the link. Thanks.

**Comment by pmwisdom** [comment]
Will do, thanks for the suggestion.
