### ISSUE TITLE
How to force the calback of the gps every time, and not wait for the gps to return a different location gps?

### ISSUE THREAD

**Issue by srsarcasmo** [pmwisdom/cordova-background-geolocation-services#71]
I can in my application cordova I can put it in the background and with it use its plugin because it seems very good, but I want the communication between the service and my app is defined every time, not have to wait for the gos to return some Value for us to be able to do a function in the background .. more qu enada to use as a timer / runnable service in android

**Comment by pmwisdom** [comment]
@srsarcasmo I don't understand what your asking. If your asking to fire a function every X seconds in the background then you need to make your own plugin that does that.

**Comment by circuitrider** [comment]
Just do $interval(function(){/*your code*/}, 15000) and set up your own timer to handle this, srsarcasmo. The service will keep you alive in the background so this should work as long as you put the timer in a scope that doesn't get disposed when the app goes into the background.
