### ISSUE TITLE
 IOS PLATFORM COMPONENT ERROR, VERSION 6

### ISSUE THREAD

**Issue by srsarcasmo** [pmwisdom/cordova-background-geolocation-services#72]
Project "Transport-app.tmp.proj" (default targets):
 Warning: Cannot include the following item(s) in your application: Plugins\cordova-background-geolocation-services-master\.gitignore;Plugins\phonegap-backgroundjs-master\.gitignore. The build system treats items with a leading dot as hidden files or directories and does not process them. If you want to include these items in your application package, rename them and rebuild your app.
 ios Build Tooling revision 2017.01.26.3r
 Build Tooling Hostname administrators-mac-3.local
 Warning: security: unable to open "'/Users/builder/Library/MobileDevice/Provisioning Profiles/2e09beed-67a9-4e81-b173-7650a6b34f79.mobileprovision'" for reading: No such file or directory
 Error: [xcode-build] Check dependencies: Swift is unavailable on iOS earlier than 7.0; please set IPHONEOS_DEPLOYMENT_TARGET to 7.0 or later (currently it is '6.0').
 Error: Buld failed
 Error: 'Build failed with error code 2'
 Done building project "Transport-app.tmp.proj" -- FAILED.

**Comment by pmwisdom** [comment]
What is your cordova version?
What version of this plugin are you using?

**Comment by srsarcasmo** [comment]
I'm using Cordova version 4

**Comment by pmwisdom** [comment]
Try updating and then try again.

**Comment by pmwisdom** [comment]
Closing this. Reopen if still a problem.
