### ISSUE TITLE
Does this library support backgroundTasks?

### ISSUE THREAD

**Issue by AsimNet** [pmwisdom/cordova-background-geolocation-services#74]
hello,

i'm writing my logic inside of `registerForLocationUpdates()`, is this the right place to do it?? or should be another way to do it, to till the OS there is an async task should be done!.

thanks.

**Comment by pmwisdom** [comment]
Yes, when you receive a location update it will go through the success callback of that registerForLocationUpdates, whatever you need to do with that location needs to be done in that callback.
