### ISSUE TITLE
Just two questions

### ISSUE THREAD

**Issue by EGreg** [pmwisdom/cordova-background-geolocation-services#77]
1. Is it free to use for both iOS and Android?

2. How does it manage to call the actual javascript callbacks from Android, if the app may be killed etc. ? What happens in that case and is it possible to send a request to a url endpoint of my choosing (with a cookie that my JS provides, to identify session / user) and update location?

**Comment by pmwisdom** [comment]
1. Yes.

2. Yes. As long as the user doesn't kill the app itself. This plugin will keep your application alive. You can do whatever you want with the location that gets sent back to your application.

**Comment by EGreg** [comment]
One more question:

Am I able to detect the mode from iOS - running, walkung, driving, etc? How about from Android? Do we get an immediate update when there is switch from eg driving to walking? Is there some unified API here that handles iOS/Android?

**Comment by pmwisdom** [comment]
Yes you can get updates from both. It is not instant, probably about 1 - 5s delay between change in activity and reporting. You can check out the possible values from android and ios documentation.

You can get the updates from the `regsiterForActivityUpdates` callback
