### ISSUE TITLE
iOS 10.2 App crashes when using Activity Updates

### ISSUE THREAD

**Issue by davinderkumar** [pmwisdom/cordova-background-geolocation-services#78]
Here is the crash log

> This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMotionUsageDescription key with a string value explaining to the user how the app uses this data.

I think plugin should add NSMotionUsageDescription in info-plist as well.

**Comment by Zerounodue** [comment]
My pull request should fix this. #79 
in the meantime you can fork and add the NSMotionUsageDescription in plugin.xml

https://github.com/pmwisdom/cordova-background-geolocation-services/pull/79/files

**Comment by pmwisdom** [comment]
Merged it. Thanks @Zerounodue .

**Comment by davinderkumar** [comment]
@pmwisdom 
Can you please tell when this fix will be available in cordova plugin? I am using Meteor so I'm not getting plugin with this fix.

**Comment by pmwisdom** [comment]
@davinderkumar Sorry I didn't see your message. I will update the meteor plugin now.
