### ISSUE TITLE
Check location provider

### ISSUE THREAD

**Issue by diegobill** [pmwisdom/cordova-background-geolocation-services#80]
How can I check location provider to consider only GPS location provider?

 Is there some variable to check location provider like in this lib https://www.npmjs.com/package/cordova-plugin-advanced-geolocation ?

**Comment by pmwisdom** [comment]
No, unfortunately there's no way to check whether the GPS data is coming from cell / wifi / etc. 

You can be pretty sure if you set the desiredAccuracy to 0 that you'll be getting data from the GPS chip.
