### ISSUE TITLE
unregisterForLocationUpdates?

### ISSUE THREAD

**Issue by Cryrivers** [pmwisdom/cordova-background-geolocation-services#81]
i `registerForLocationUpdates` multiple times (from time to time). Is it necessary to have an `unregisterForLocationUpdates`?

**Comment by pmwisdom** [comment]
Your most recent `registerForLocationUpdates` *should* overwrite all the past callbacks. You should only get a location update from one callback at a time. I didn't write in support for multiple listeners so thats the way it should act.

Although I haven't tested it out so there may be different behavior. Let me know if thats not what you observe

**Comment by Cryrivers** [comment]
@pmwisdom got it. i wrap the background positioning logic in an `Observable` and just have no idea how to do the cleanups. currently I put `backgroundLocationServices.stop()` in the cleanup callback and it seems to behave correctly.
