### ISSUE TITLE
No Documentation on how to use in ionic application. 

### ISSUE THREAD

**Issue by vkbrulex** [pmwisdom/cordova-background-geolocation-services#86]
NO demo app or documentation provided to include this n ionic v1 APP.

making service is not working.

**Comment by pmwisdom** [comment]
I posted this on SO awhile ago, its no different for any other cordova based framework, in that you just need to wait for cordova to be ready. Check out the link below.

https://stackoverflow.com/questions/32400335/gps-position-when-mobile-app-is-in-background-with-ionicframework/33403045#33403045
