### ISSUE TITLE
Can't install plugin 

### ISSUE THREAD

**Issue by jackie19** [pmwisdom/cordova-background-geolocation-services#9]
W:\Temp\walker>cordova plugin add ./cordova-background-geolocation-services-master
Installing "org.flybuy.cordova.background-location-services" for android
WARNING: org.apache.cordova.geolocation has been renamed to cordova-plugin-geolocation. You may not be getting the latest version! We suggest you `cordova plug
in rm org.apache.cordova.geolocation` and `cordova plugin add cordova-plugin-geolocation`.
Fetching plugin "org.apache.cordova.geolocation" via cordova plugins registry
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apache.cordova.geolocation/-/org.apache.cordova.geolocation-0.3.12.tgz
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apache.cordova.geolocation/-/org.apache.cordova.geolocation-0.3.12.tgz
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apache.cordova.geolocation/-/org.apache.cordova.geolocation-0.3.12.tgz
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apache.cordova.geolocation/-/org.apache.cordova.geolocation-0.3.12.tgz
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apache.cordova.geolocation/-/org.apache.cordova.geolocation-0.3.12.tgz
npm ERR! fetch failed http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apache.cordova.geolocation/-/org.apache.cordova.geolocation-0.3.12.tgz
Fetching from cordova plugins registry failed: getaddrinfo EAI_AGAIN cordova.iriscouch.com:80
Fetching plugin "org.apache.cordova.geolocation" via npm
npm http GET https://registry.npmjs.org/org.apache.cordova.geolocation
npm http 404 https://registry.npmjs.org/org.apache.cordova.geolocation
TypeError: Cannot read property 'latest' of undefined
    at next (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\lib\cache.js:687:35)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\lib\cache.js:675:5
    at saved (C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-client\lib\get.js:142
:7)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\graceful-fs\polyfills.js:133:7
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by pmwisdom** [comment]
What version of cordova are you running so I can run it against that?

**Comment by pmwisdom** [comment]
Try Latest Commit https://github.com/pmwisdom/cordova-background-geolocation-services/commit/1f4432508895c7eb9825cc129ccbdafc453ae44a.

**Comment by dongzhl** [comment]
Error: Failed to fetch plugin https://github.com/pmwisdom/cordova-background-geolocation-services.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/pmwisdom/cordova-background-geolocation-services.git /Users/maca/.npm/_cacache/tmp/git-clone-1d93cb61
npm ERR! /Users/maca/.npm/_cacache/tmp/git-clone-1d93cb61/.git: Permission denied
