### ISSUE TITLE
Error on install plugin ionic 3 project

### ISSUE THREAD

**Issue by GivailsonNeves** [pmwisdom/cordova-background-geolocation-services#92]
cordova plugin add https://github.com/pmwisdom/cordova-background-geolocation-services.git --save

"Error: Failed to fetch plugin https://github.com/pmwisdom/cordova-background-geolocation-services.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module"

everithing is ok with my connection, i have try another plugins and they install normally.

**Comment by filipeoliveira** [comment]
Same error here. Did you found a solution?

**Comment by GivailsonNeves** [comment]
My problem was the internet of my job. In another computer with another connection everything goes fine.
