### ISSUE TITLE
[HELP] Cannot read property 'backgroundLocationServices' of undefined

### ISSUE THREAD

**Issue by bhagaym** [pmwisdom/cordova-background-geolocation-services#94]
Hello,
I have try to add and run this plugin but I have an error that said "Cannot read property 'backgroundLocationServices' of undefined".
My steps is:
1. cordova plugin add https://github.com/pmwisdom/cordova-background-geolocation-services.git --save
2. Copy all script in 'How to use' in my index.html
3. Run it with cordova run browser

Anyone can help?
thanks

**Comment by pmwisdom** [comment]
You cannot run cordova plugins in the browser, they need access to native libraries. aka you need to run cordova run ios / android.
